### ISSUE TITLE
`wasm32` is not valid cpu value

### ISSUE THREAD

**Issue by smorimoto** [napi-rs/node-rs#792]
`cpu` in `package.json` refers to `process.arch`, but `wasm 32` is not a valid value.

https://github.com/napi-rs/node-rs/blob/de1e89bfd55f444090e4d3dc97dc5772ddd89296/packages/bcrypt/npm/wasm32-wasi/package.json#L4-L6

This might cause an error such as the following:

```
Module not found: Can't resolve '@node-rs/bcrypt-wasm32-wasi'
```

### Ref

- https://docs.npmjs.com/cli/v10/configuring-npm/package-json#cpu
- https://nodejs.org/api/process.html#processarch

**Comment by Brooooooklyn** [comment]
We decided to adopt this strategy for releasing the `wasm` package as discussed in the following issue: https://github.com/napi-rs/napi-rs/issues/1794

If you encounter any issues, comments are welcome in the original issue.

**Comment by smorimoto** [comment]
Vercel's edge runtime seems to resolve the browser, which requires wasm code, but in the current setup it is not installed in typical environments. It might not be ideal, but it might be helpful to get rid of the cpu constraint to work around the weird error with Next.js + edge runtime.

**Comment by Brooooooklyn** [comment]
@smorimoto For the edge runtime scenario, you can use `npm install --cpu=wasm32` to let the package manager pick the right dependency.

**Comment by smorimoto** [comment]
You can't use it with yarn. And in esbuild, nothing is specified: https://github.com/evanw/esbuild/blob/main/npm/esbuild-wasm/package.json

**Comment by smorimoto** [comment]
That pointer definitely helped me! Thank you!

**Comment by adumesny** [comment]
I would to add that `cpu=wasm32` and forcing user to install this makes no sense to me. while it's easy to `yarn install --ignore-platform` for this module, it makes `yarn` to install on build machines and other other devs fail because that yarn.lock file entry doesn't match your machine going forward...

maybe my problem is that even though we targerting browsers, esbuild is for some reasonc picking this package which traditionally only have .node binary that wouldn't browser work anyway and this lib really should not be used...

**Comment by victormihalache** [comment]
What about `pnpm`? There's no `--ignore-platform` or `--cpu=wasm32` option
