### ISSUE TITLE
node-rs/crc32 Error: Unsupported architecture on Linux: ia32

### ISSUE THREAD

**Issue by trollcop** [napi-rs/node-rs#903]
Error: Unsupported architecture on Linux: ia32
    at Object.<anonymous> (/usr/local/lib/node_modules/@node-rs/crc32/index.js:181:15)

This supports everything else, including 32 bit arm, and 32 bit on msvc, so really what is the point of NOT supporting ia32 on Linux?
I've got an old atom box where I was going to run some stuff but it depends on this module and isn't working because someone decided not to support anything except x64.

**Comment by Brooooooklyn** [comment]
You can use `wasm` version for your env by install with `npm install --cpu=wasm32`

We supports the `armv7` on Linux and i686 on Windows because there are official Node.js releases for these platform. But there are no official `node:lts` Docker image for Linux ia32 env, so we can't test the prebuild binaries for these platform.

**Comment by Brooooooklyn** [comment]
you can use `npm install --cpu=wasm32 mirakurun` to use `wasm32` fallback in your env

**Comment by trollcop** [comment]
running this made no difference, the same missing ia32 error comes up.

**Comment by trollcop** [comment]
I noticed that this particular module was only used in one extremely not performance critical piece, so I'm just going to reach out to mirakurun maintainers to stop using this rust mess and just pick any other crc32 code that just works.

**Comment by Brooooooklyn** [comment]
It seems like your npm cli is too old to support --cpu arg..
